[package]
name = "logprep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
regex = "1.11.1"
sha2 = "0.10.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10"
once_cell = "1.21.3"
